GET http://localhost:4000/filmes

###

GET http://localhost:4000/filmes/FIL001

###

GET http://localhost:4000/filmes/FIL002

###

GET http://localhost:4000/filmes/FIL003

###

POST http://localhost:4000/filmes
Content-Type: application/json


{id: "FIL001",
titulo: "Cidade de Deus",
ano: 2002,
genero: [
    { id: "GEN001", nome: "Crime" },
    { id: "GEN002", nome: "Drama" },
],
diretor: {
    id: "DIR001",
    nome: "Fernando Meirelles",
    nascimento: "1955-11-09",
    nacionalidade: "Brasileiro",
}
},

POST http://localhost:4000/filmes
Content-Type: application/json

{
  "titulo": "Filme 4",
  "ano": 2024
}

